<h1>3.1 数据基础运算工具：NumPy<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#3.1.1-常见数据结构" data-toc-modified-id="3.1.1-常见数据结构-3">3.1.1 常见数据结构</a></span><ul class="toc-item"><li><span><a href="#1.列表" data-toc-modified-id="1.列表-3.1">1.列表</a></span><ul class="toc-item"><li><span><a href="#（1）创建列表" data-toc-modified-id="（1）创建列表-3.1.1">（1）创建列表</a></span></li><li><span><a href="#（2）列表的方法" data-toc-modified-id="（2）列表的方法-3.1.2">（2）列表的方法</a></span></li></ul></li><li><span><a href="#2.元组" data-toc-modified-id="2.元组-3.2">2.元组</a></span><ul class="toc-item"><li><span><a href="#（1）创建元组" data-toc-modified-id="（1）创建元组-3.2.1">（1）创建元组</a></span></li><li><span><a href="#（2）元组赋值" data-toc-modified-id="（2）元组赋值-3.2.2">（2）元组赋值</a></span></li></ul></li><li><span><a href="#3.集合" data-toc-modified-id="3.集合-3.3">3.集合</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#1）集合A与集合B的差集" data-toc-modified-id="1）集合A与集合B的差集-3.3.0.1">1）集合A与集合B的差集</a></span></li><li><span><a href="#2）集合A与集合B的并集" data-toc-modified-id="2）集合A与集合B的并集-3.3.0.2">2）集合A与集合B的并集</a></span></li><li><span><a href="#3）集合A与集合B的交集" data-toc-modified-id="3）集合A与集合B的交集-3.3.0.3">3）集合A与集合B的交集</a></span></li></ul></li></ul></li><li><span><a href="#4.字典" data-toc-modified-id="4.字典-3.4">4.字典</a></span></li></ul></li><li><span><a href="#3.1.2-索引和切片" data-toc-modified-id="3.1.2-索引和切片-4">3.1.2 索引和切片</a></span></li><li><span><a href="#3.1.3-数组运算" data-toc-modified-id="3.1.3-数组运算-5">3.1.3 数组运算</a></span><ul class="toc-item"><li><span><a href="#1.创建数组" data-toc-modified-id="1.创建数组-5.1">1.创建数组</a></span></li><li><span><a href="#2.常用运算" data-toc-modified-id="2.常用运算-5.2">2.常用运算</a></span></li></ul></li><li><span><a href="#3.1.4-矩阵运算" data-toc-modified-id="3.1.4-矩阵运算-6">3.1.4 矩阵运算</a></span><ul class="toc-item"><li><span><a href="#1.创建矩阵" data-toc-modified-id="1.创建矩阵-6.1">1.创建矩阵</a></span></li><li><span><a href="#2.常见的矩阵运算" data-toc-modified-id="2.常见的矩阵运算-6.2">2.常见的矩阵运算</a></span><ul class="toc-item"><li><span><a href="#（1）矩阵相乘" data-toc-modified-id="（1）矩阵相乘-6.2.1">（1）矩阵相乘</a></span></li><li><span><a href="#（2）矩阵点乘" data-toc-modified-id="（2）矩阵点乘-6.2.2">（2）矩阵点乘</a></span></li><li><span><a href="#（3）矩阵转置" data-toc-modified-id="（3）矩阵转置-6.2.3">（3）矩阵转置</a></span></li></ul></li></ul></li><li><span><a href="#3.1.5-广播" data-toc-modified-id="3.1.5-广播-7">3.1.5 广播</a></span></li><li><span><a href="#3.1.6-其他常用操作" data-toc-modified-id="3.1.6-其他常用操作-8">3.1.6 其他常用操作</a></span><ul class="toc-item"><li><span><a href="#1.数组排序" data-toc-modified-id="1.数组排序-8.1">1.数组排序</a></span></li><li><span><a href="#2.数组统计" data-toc-modified-id="2.数组统计-8.2">2.数组统计</a></span></li><li><span><a href="#3.线性代数" data-toc-modified-id="3.线性代数-8.3">3.线性代数</a></span></li><li><span><a href="#4.随机数生成" data-toc-modified-id="4.随机数生成-8.4">4.随机数生成</a></span></li></ul></li></ul></div>

# 3.1.1 常见数据结构

## 1.列表 

### （1）创建列表

In [1]:
list1 = ['wellcom','to','the','sjwjyaisf1688']
list1

['wellcom', 'to', 'the', 'sjwjyaisf1688']

In [2]:
list2 = ['wellcom','to','the','sjwjyaisf1688',6,6,6]
list2

['wellcom', 'to', 'the', 'sjwjyaisf1688', 6, 6, 6]

In [3]:
list(['xiao','xiao','wa','jue','ji',666])

['xiao', 'xiao', 'wa', 'jue', 'ji', 666]

In [4]:
list('666')

['6', '6', '6']

In [5]:
['wellcom','to','te']+['xiao','xiao','ji','666']

['wellcom', 'to', 'te', 'xiao', 'xiao', 'ji', '666']

### （2）列表的方法

In [6]:
list2 = ['a','b','c']
list2.append('d')
list2

['a', 'b', 'c', 'd']

In [7]:
list3 = ['e','f']
list2+list3

['a', 'b', 'c', 'd', 'e', 'f']

In [8]:
list2 = [0,1,2]
list2.extend([3,4,5])
list2

[0, 1, 2, 3, 4, 5]

## 2.元组

### （1）创建元组

In [9]:
tuple1=1,2,3
tuple2="sjwjyaisf1688","xiaoxiaowajueji666"
tuple3=(1,2,3,4)
tuple4=()
tuple5=(1,)

In [10]:
print(tuple1,tuple2,tuple3,tuple4,tuple5) 

(1, 2, 3) ('sjwjyaisf1688', 'xiaoxiaowajueji666') (1, 2, 3, 4) () (1,)


In [11]:
(1,2,3)+(4,5,6)

(1, 2, 3, 4, 5, 6)

### （2）元组赋值

In [12]:
list2[1]='a'
list2

[0, 'a', 2, 3, 4, 5]

In [13]:
tuple1[1] = 'a'
tuple1

TypeError: 'tuple' object does not support item assignment

## 3.集合

In [14]:
drink = {'water','milk','lemonade','beer','sprite'}
drink

{'beer', 'lemonade', 'milk', 'sprite', 'water'}

In [15]:
drink =set(['water','milk','lemonade','beer','sprite','milk','sprite'])
drink

{'beer', 'lemonade', 'milk', 'sprite', 'water'}

In [16]:
A = {1,2,3,4,5,6}
B = {3,4,5}

#### 1）集合A与集合B的差集

In [17]:
A - B  

{1, 2, 6}

#### 2）集合A与集合B的并集

In [18]:
A | B

{1, 2, 3, 4, 5, 6}

#### 3）集合A与集合B的交集

In [19]:
A & B

{3, 4, 5}

## 4.字典

In [20]:
dict1 = {'xiaoming':24,'xiaofang':28,'zhangsan':21,'wangwu':27}
dict1

{'xiaoming': 24, 'xiaofang': 28, 'zhangsan': 21, 'wangwu': 27}

In [21]:
dict1.keys()

dict_keys(['xiaoming', 'xiaofang', 'zhangsan', 'wangwu'])

In [22]:
dict1.values()

dict_values([24, 28, 21, 27])

In [23]:
dict1['xiaoming']

24

In [24]:
dict2 = {'xiaoming':24,'xiaofang':28,'zhangsan':21,'wangwu':27,'xiaoming':25}
dict2

{'xiaoming': 25, 'xiaofang': 28, 'zhangsan': 21, 'wangwu': 27}

# 3.1.2 索引和切片

In [25]:
list1 = ['wellcom','to','the','sjwjyaisf1688',6,6,6]
list1[0]

'wellcom'

In [26]:
list1[2:4]

['the', 'sjwjyaisf1688']

In [27]:
list1[-1]

6

In [28]:
list1[-3:]

[6, 6, 6]

In [29]:
tuple3 =(1,2,3,4)
tuple3[0]

1

In [30]:
tuple3[1:2]

(2,)

In [31]:
tuple3[-3:]

(2, 3, 4)

# 3.1.3 数组运算

## 1.创建数组

In [32]:
import numpy as np

In [33]:
data1 = [5.5,6.0,7,2,4.5]
array1 = np.array(data1)
array1

array([5.5, 6. , 7. , 2. , 4.5])

In [34]:
data2 =[[1,2,3],[4,5,6]]
array2 = np.array(data2)
array2

array([[1, 2, 3],
       [4, 5, 6]])

In [35]:
data3 = [[[1,2,3],[4,5,6],[7,8,9]]]
array3 = np.array(data3)
array3

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [36]:
array2.ndim

2

In [37]:
array2.shape

(2, 3)

In [38]:
array3.ndim

3

In [39]:
array3.shape

(1, 3, 3)

In [40]:
array1.dtype

dtype('float64')

In [41]:
array2.dtype

dtype('int32')

In [42]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [43]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [44]:
np.empty((3,5,3))

array([[[5.37500933e-317, 1.31338004e-311, 3.09759523e-312],
        [0.00000000e+000, 1.69484279e-319, 3.09759523e-312],
        [0.00000000e+000, 1.31325885e-311, 0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 1.31325870e-311],
        [2.47032823e-323, 6.95287364e-310, 2.02369289e-320]],

       [[2.47032823e-323, 6.95287364e-310, 9.88131292e-324],
        [0.00000000e+000, 0.00000000e+000, 4.85686292e-319],
        [0.00000000e+000,             nan, 0.00000000e+000],
        [4.67296746e-307, 1.69121096e-306, 4.67293691e-307],
        [1.33508845e-306, 1.33511969e-306, 6.23037996e-307]],

       [[6.23053954e-307, 9.34609790e-307, 8.45593934e-307],
        [9.34600963e-307, 1.86921143e-306, 6.23061763e-307],
        [8.90104239e-307, 6.89804132e-307, 1.39071275e-307],
        [8.34426039e-308, 1.27946076e-307, 1.33511562e-306],
        [8.90103560e-307, 1.42410974e-306, 3.23796840e-317]]])

## 2.常用运算

In [45]:
data = np.array([[0.9,0.35,0.14,0.46],[0.53,0.78,0.12,0.86]])
data

array([[0.9 , 0.35, 0.14, 0.46],
       [0.53, 0.78, 0.12, 0.86]])

In [46]:
data + data

array([[1.8 , 0.7 , 0.28, 0.92],
       [1.06, 1.56, 0.24, 1.72]])

In [47]:
data - data

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
data * data

array([[0.81  , 0.1225, 0.0196, 0.2116],
       [0.2809, 0.6084, 0.0144, 0.7396]])

In [49]:
data / data

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [50]:
data * 2

array([[1.8 , 0.7 , 0.28, 0.92],
       [1.06, 1.56, 0.24, 1.72]])

In [51]:
data + 3*data

array([[3.6 , 1.4 , 0.56, 1.84],
       [2.12, 3.12, 0.48, 3.44]])

In [52]:
3*data - data/2

array([[2.25 , 0.875, 0.35 , 1.15 ],
       [1.325, 1.95 , 0.3  , 2.15 ]])

In [53]:
data1 = np.array([[-0.9,0.35,0.14,-0.46],[0.53,-0.78,-0.12,-0.86]])
data1

array([[-0.9 ,  0.35,  0.14, -0.46],
       [ 0.53, -0.78, -0.12, -0.86]])

In [54]:
np.abs(data1)

array([[0.9 , 0.35, 0.14, 0.46],
       [0.53, 0.78, 0.12, 0.86]])

In [55]:
np.sqrt(data1)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


array([[       nan, 0.59160798, 0.37416574,        nan],
       [0.72801099,        nan,        nan,        nan]])

In [56]:
np.square(data1)

array([[0.81  , 0.1225, 0.0196, 0.2116],
       [0.2809, 0.6084, 0.0144, 0.7396]])

In [57]:
np.exp(data1)

array([[0.40656966, 1.41906755, 1.1502738 , 0.63128365],
       [1.69893231, 0.45840601, 0.88692044, 0.42316208]])

In [58]:
np.log2(data1)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log2
  """Entry point for launching an IPython kernel.


array([[        nan, -1.51457317, -2.83650127,         nan],
       [-0.91593574,         nan,         nan,         nan]])

In [59]:
np.log10(data1)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log10
  """Entry point for launching an IPython kernel.


array([[        nan, -0.45593196, -0.85387196,         nan],
       [-0.27572413,         nan,         nan,         nan]])

# 3.1.4 矩阵运算

## 1.创建矩阵

In [60]:
data = np.array([[0.9,0.35,0.14,0.46],[0.53,0.78,0.12,0.86]])
mat = np.mat(data)
mat

matrix([[0.9 , 0.35, 0.14, 0.46],
        [0.53, 0.78, 0.12, 0.86]])

In [61]:
np.shape(mat)

(2, 4)

In [62]:
data0 = np.matrix(np.zeros((4,4)))
data0

matrix([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [63]:
data1 = np.matrix(np.ones((4,4)))
data1

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [64]:
data2=np.matrix(np.random.rand(2,2))
data2

matrix([[0.77072301, 0.13693513],
        [0.37899454, 0.27655442]])

In [65]:
data3=np.matrix(np.random.randint(10,size=(3,3)))
data3

matrix([[2, 3, 2],
        [8, 7, 8],
        [1, 9, 2]])

## 2.常见的矩阵运算

### （1）矩阵相乘

In [66]:
a1 = np.matrix([1,2]) 
a2 = np.matrix([[1],[2]])
a3 = a1*a2
a3

matrix([[5]])

In [67]:
a1 = np.matrix([1,2]) 
a2 = np.matrix([[1],[2],[3]])
a3 = a1*a2
a3

ValueError: shapes (1,2) and (3,1) not aligned: 2 (dim 1) != 3 (dim 0)

### （2）矩阵点乘

In [68]:
a1 = np.matrix([2,2])
a2 = np.matrix([3,3])
a3 = np.multiply(a1,a2)
a3

matrix([[6, 6]])

In [69]:
a1 = np.matrix([2,2])
a2 = a1*3
a2

matrix([[6, 6]])

### （3）矩阵转置

In [70]:
a1 = np.matrix([[1,1],[0,0]])
a2 = a1.T
a2

matrix([[1, 0],
        [1, 0]])

# 3.1.5 广播

In [71]:
a = np.matrix([1,2,3])
result = a + 100
result

matrix([[101, 102, 103]])

In [72]:
b = np.matrix([[1,2,3],[4,5,6]])
result1 = b + [100, 200, 300]
result1

matrix([[101, 202, 303],
        [104, 205, 306]])

# 3.1.6 其他常用操作

## 1.数组排序

In [73]:
array1 = np.random.randn(8)
array1

array([-1.032974  ,  0.46992421, -0.23335726,  0.27710566,  0.22723403,
        0.79556031,  0.05487751, -0.70310145])

In [74]:
np.sort(array1)

array([-1.032974  , -0.70310145, -0.23335726,  0.05487751,  0.22723403,
        0.27710566,  0.46992421,  0.79556031])

In [75]:
array2 = np.random.randint(0,10,size=(3,3))
array2

array([[8, 8, 8],
       [9, 7, 9],
       [1, 5, 5]])

In [76]:
np.sort(array2,axis=0)

array([[1, 5, 5],
       [8, 7, 8],
       [9, 8, 9]])

In [77]:
np.sort(array2,axis=1)

array([[8, 8, 8],
       [7, 9, 9],
       [1, 5, 5]])

## 2.数组统计

In [78]:
array3 = np.array([[1,2,3],[4,5,6],[7,8,9]])
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
array3.sum()

45

In [80]:
array3.sum(axis=0)

array([12, 15, 18])

In [81]:
array3.mean()

5.0

In [82]:
array3.mean(axis=1)

array([2., 5., 8.])

In [83]:
array3.min()

1

In [84]:
array3.max()

9

## 3.线性代数

In [85]:
a = np.array([[1.5,2.5,3.5],[4.5,5.5,6.6]])
a

array([[1.5, 2.5, 3.5],
       [4.5, 5.5, 6.6]])

In [86]:
b = np.array([[4.0,6.8],[-2.3,9.6],[5.2,6.1]])
b

array([[ 4. ,  6.8],
       [-2.3,  9.6],
       [ 5.2,  6.1]])

In [87]:
a.dot(b)

array([[ 18.45,  55.55],
       [ 39.67, 123.66]])

In [88]:
from numpy.linalg import inv
X = np.matrix(np.random.rand(3,3))
X

matrix([[0.14591771, 0.63476607, 0.6434783 ],
        [0.90963842, 0.93582579, 0.89333056],
        [0.5082369 , 0.37614992, 0.92365896]])

In [89]:
inv(X)

matrix([[-2.08087463,  1.35583966,  0.13834616],
        [ 1.52089357,  0.75719822, -1.79188466],
        [ 0.52561963, -1.05440193,  1.73625191]])

In [90]:
X.I

matrix([[-2.08087463,  1.35583966,  0.13834616],
        [ 1.52089357,  0.75719822, -1.79188466],
        [ 0.52561963, -1.05440193,  1.73625191]])

## 4.随机数生成

In [91]:
samples = np.random.normal(size=(3,3))
samples

array([[-0.83324744, -0.63028865, -0.76287782],
       [-1.57998563,  0.29177508,  1.46526463],
       [-1.84215818,  0.85769578, -0.92848963]])

In [92]:
samples1 = np.random.rand(4,4)
samples1

array([[0.8418087 , 0.84087399, 0.35946675, 0.61561178],
       [0.98581591, 0.87808207, 0.53668364, 0.90679142],
       [0.278527  , 0.99715024, 0.11061937, 0.36795292],
       [0.35597455, 0.88758454, 0.1608014 , 0.04269731]])

In [93]:
samples3 = np.random.randint(0,10,size=(4,6))
samples3

array([[4, 9, 7, 2, 2, 9],
       [7, 5, 9, 2, 7, 1],
       [1, 3, 6, 5, 5, 1],
       [2, 9, 1, 9, 4, 9]])